# Generated by Django 4.1.6 on 2023-02-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_tags',
            new_name='tags',
        ),
    ]
